namespace LaVie.Extras.Enums;

public enum PERMISSIONS
{
    HOME_INDEX,
    USER_CREATE,
    USER_INDEX,
    USER_UPDATE,
    USER_DELETE,
    ROLE_UPDATE,
    CATEGORY_CREATE,
    CATEGORY_INDEX,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,
    TAG_CREATE,
    TAG_INDEX,
    TAG_UPDATE,
    TAG_DELETE,
    PRODUCT_CREATE,
    PRODUCT_INDEX,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
}
